apiVersion: v1
data:
  sidecar.automountServiceAccountToken: "true"
  sidecar.container: |
    args:
    - status
    - --provider
    - gitlab
    - --target
    - https://172.11.0.6:30298
    - --token=h-zez9CWzyzykbLoS53s
    - --username=zhaoxiaojie
    - --server=http://10.121.218.82:6080/
    - --create-comment=true
    - --comment-identity=AILink workflow status report.
    image: ghcr.io/linuxsuren/workflow-executor-gogit:v0.0.13
    imagePullPolicy: IfNotPresent
    command:
    - workflow-executor-gogit
    name: gogit-executor-plugin
    env:
    - name: TZ
      value: Asia/Shanghai
    ports:
    - containerPort: 3001
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: true
      runAsNonRoot: true
      runAsUser: 65534
kind: ConfigMap
metadata:
  labels:
    workflows.argoproj.io/configmap-type: ExecutorPlugin
  name: gogit-executor-plugin
  namespace: argo
