apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-addition
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - "argoproj.io"
  resources:
  - workflowtasksets/status
  verbs:
  - patch
- apiGroups:
  - "argoproj.io"
  resources:
  - workflows
  verbs:
  - get
  - list
  - update
