apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: pr-snrclient
  namespace: default
spec:
  event:
    selector: payload.event_type == "merge_request" && payload.project.name == "SonatypeNexusRepositoryClient" && payload.object_attributes.state == "opened"
  submit:
    workflowTemplateRef:
      name: pr-snrclient
    arguments:
      parameters:
      - name: branch
        valueFrom:
          event: payload.object_attributes.source_branch
      - name: pr
        valueFrom:
          event: payload.object_attributes.iid